travis:
  secure:
    BINSTAR_TOKEN: nFm6diyiNck1x/Y7GxvDcmgc+R3GyFN/ARYgGKsxhfPPVrqLjQhzx0g0tJN0OAeV/YvBly6X49h5LI3Q83bKQKZhAMiyodeCVFWTpM7wUKqZEKHJl4JAb6XJUIpeMA99hEdFyTQzYRxvzHYpqZljIJ/2rBto8ktZafaJcRhmeJCwpeXd7Weqodx5pndDATUi6dzelkzAPrIPdoLEAC2pHXIaeQX7tsYtG3HPTjT/2Ivicm4xKE3lUhs7E9XUZgCqOvysHztn71CizIz+pLEVEXat/+Gvl3n+ucIBllFn+pL0OjwsGympH+RSVG9Xglg+lpztP2d0ZwPM+tWqF4OgTcLC+SkDk+HkpL9geJRzC3jbhh0I7KehGZSgk0JbbhDOpe3q5abKG1lKp1ZonQilwq9y/Uam2m829Ues1piBVrEb563374JEYIOK/Bp0W2S/MPyhrss4Q5jsCeV/jOrr5i94ErA8tDjU53ErFXxQMpOeTVPZtP4ijqcXkKx6eVzlmBL8sLQkQOhxW0EfCWO31+rKwRt9Xp8g0Ic6bkhgwnBLwO//JBnZoZoX6Uct6J15djl+z1rQOUUfwLqrcVyUR+2Am0jaBMZ+INavjYb3TGJ7PUs0O7BaldxgSMXGI0a1vK/FPsn7U8DR0A3mBRQlLYXvFsvaLYKQG0pmlyJZ5lA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
